### ISSUE TITLE
Add icons to alerts

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/complaint-tracking#686]
[Alerts · Bootstrap v5.3](https://getbootstrap.com/docs/5.3/components/alerts/#icons)

**Comment by AnukratiMehta** [comment]
@dougwaldron I'd like to work on this. Please assign.

**Comment by dougwaldron** [comment]
@AnukratiMehta That would be great! Thanks for offering to help.

**Comment by AnukratiMehta** [comment]
@dougwaldron Please share setup instructions.

**Comment by dougwaldron** [comment]
Hi @AnukratiMehta, it seems I had introduced an error a while back without realizing it so that the app wouldn't run directly after cloning the repo. I believe I've fixed it now.

Please clone the repo and check out the `vNext/main` branch. Or, if you've already cloned it, you can pull the latest changes to that branch.

Then you should be able to run `dotnet build` followed by `dotnet run --project .\src\WebApp\` from the project root. Please let me know if you have any trouble getting started.

**Comment by AnukratiMehta** [comment]
The build is successful but I'm still getting an error on running, @dougwaldron 

```
An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.
complaint-tracking/src/WebApp/Pages/Shared/_RaygunScriptsPartial.cshtml

'AppSettings' is inaccessible due to its protection level
+
    var apiKey = AppSettings.RaygunSettings.ApiKey;
```

**Comment by dougwaldron** [comment]
@AnukratiMehta Sorry this has been difficult to work with! 

I don't know why you're getting that error. It works for me from a clean clone, and there shouldn't be any issues with AppSettings protection level.

Can you please try starting over by cloning again and see if it works? If not, what development environment are you using? Where are you seeing the error message?

**Comment by AnukratiMehta** [comment]
Thanks, @dougwaldron! A clean clone worked for me as well.
